# Generated by Django 4.2.4 on 2023-11-15 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_ticket_passengers_ticket_passengers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
